### ISSUE TITLE
[Feature]: Transform requireActual to importActual with async/await

### ISSUE THREAD

**Issue by jgoz** [trivikr/vitest-codemod#83]
### Self-service

- [X] I'd be willing to implement this feature

### Template name

jest

### Input code

```ts
jest.mock('some-module', () => {
  const actual = jest.requireActual('some-module');
  return {
    ...actual,
    mocked: jest.fn(),
  };
});
```

### Expected Output

```ts
import { vi } from 'vitest';
vi.mock('some-module', async () => {
  const actual = await vi.importActual('some-module');
  return {
    ...actual,
    mocked: vi.fn(),
  };
});
```

### Additional context

This could also be done for `requireMock`/`importMock`

**Comment by trivikr** [comment]
Transformation of jest to vi was added in https://github.com/trivikr/vitest-codemod/pull/80, and released in vitest-codemod@0.1.2

It converts provided code to the following though:

```ts
import { vi } from "vitest";
vi.mock('some-module', () => {
  const actual = vi.requireActual('some-module');
  return {
    ...actual,
    mocked: vi.fn(),
  };
});
```

Two things would be needed:
* The mapping between jest.requireActual and vi.importActual needs to be added.
  * A utility similar to `replaceTestApiFailing` can be added, say `replaceJestApiRequire`
* The await will have to be added to vi API, and function call will have to made async
  * Await can be done in utility `replaceJestApiRequire`, but making function call async can break stuff.
 
Is there a simpler code transform can output?

**Comment by trivikr** [comment]
Looking at the discussions, requireActual won't be supported
https://github.com/vitest-dev/vitest/discussions/940#discussioncomment-2365087

**Comment by trivikr** [comment]
I couldn't find a better solution.

I think the transform should rename the API for this specific case only.
i.e. Convert API `requireActual` to `importActual` only in the callback of `.mock`, adding await and async as needed.
